export const AIRPORT_CODES = [
  { value: 'ATL', name: 'ATL | Hartsfield–Jackson Atlanta International Airport (USA)' },
  { value: 'PEK', name: 'PEK | Beijing Capital International Airport (China)' },
  { value: 'LAX', name: 'LAX | Los Angeles International Airport (USA)' },
  { value: 'DXB', name: 'DXB | Dubai International Airport (UAE)' },
  { value: 'HND', name: 'HND | Tokyo Haneda Airport (Japan)' },
  { value: 'ORD', name: 'ORD | O’Hare International Airport (USA)' },
  { value: 'LHR', name: 'LHR | London Heathrow Airport (UK)' },
  { value: 'HKG', name: 'HKG | Hong Kong International Airport (Hong Kong)' },
  { value: 'PVG', name: 'PVG | Shanghai Pudong International Airport (China)' },
  { value: 'CDG', name: 'CDG | Charles de Gaulle Airport (France)' },
  { value: 'DFW', name: 'DFW | Dallas/Fort Worth International Airport (USA)' },
  { value: 'AMS', name: 'AMS | Amsterdam Airport Schiphol (Netherlands)' },
  { value: 'FRA', name: 'FRA | Frankfurt am Main Airport (Germany)' },
  { value: 'IST', name: 'IST | Istanbul Airport (Turkey)' },
  { value: 'SIN', name: 'SIN | Singapore Changi Airport (Singapore)' },
  { value: 'ICN', name: 'ICN | Incheon International Airport (South Korea)' },
  { value: 'JFK', name: 'JFK | John F. Kennedy International Airport (USA)' },
  { value: 'CAN', name: 'CAN | Guangzhou Baiyun International Airport (China)' },
  { value: 'DEN', name: 'DEN | Denver International Airport (USA)' },
  { value: 'BKK', name: 'BKK | Suvarnabhumi Airport (Thailand)' },
  { value: 'MIA', name: 'MIA | Miami International Airport (USA)' },
  { value: 'MEX', name: 'MEX | Mexico City International Airport (Mexico)' },
  { value: 'GRU', name: 'GRU | São Paulo/Guarulhos International Airport (Brazil)' },
  { value: 'EZE', name: 'EZE | Ministro Pistarini International Airport (Argentina)' },
  { value: 'GIG', name: 'GIG | Rio de Janeiro/Galeão International Airport (Brazil)' },
  { value: 'BOG', name: 'BOG | El Dorado International Airport (Colombia)' },
  { value: 'SCL', name: 'SCL | Comodoro Arturo Merino Benítez Airport (Chile)' },
  { value: 'LIM', name: 'LIM | Jorge Chávez International Airport (Peru)' },
  { value: 'PTY', name: 'PTY | Tocumen International Airport (Panama)' },
  { value: 'MUC', name: 'MUC | Munich Airport (Germany)' },
  { value: 'BCN', name: 'BCN | Barcelona–El Prat Airport (Spain)' },
  { value: 'MAD', name: 'MAD | Madrid–Barajas Airport (Spain)' },
  { value: 'YYZ', name: 'YYZ | Toronto Pearson International Airport (Canada)' },
  { value: 'YVR', name: 'YVR | Vancouver International Airport (Canada)' },
  { value: 'SYD', name: 'SYD | Sydney Kingsford Smith Airport (Australia)' },
  { value: 'MEL', name: 'MEL | Melbourne Airport (Australia)' },
  { value: 'GUA', name: 'GUA | La Aurora International Airport (Guatemala)' },
  { value: 'UIO', name: 'UIO | Mariscal Sucre International Airport (Ecuador)' },
  { value: 'GYE', name: 'GYE | José Joaquín de Olmedo Airport (Ecuador)' },
  { value: 'CUN', name: 'CUN | Cancun International Airport (Mexico)' },
  { value: 'PHX', name: 'PHX | Phoenix Sky Harbor International Airport (USA)' },
  { value: 'SEA', name: 'SEA | Seattle–Tacoma International Airport (USA)' },
  { value: 'CLT', name: 'CLT | Charlotte Douglas International Airport (USA)' },
  { value: 'LAS', name: 'LAS | Harry Reid International Airport (USA)' },
  { value: 'IAH', name: 'IAH | George Bush Intercontinental Airport (USA)' },
  { value: 'MSP', name: 'MSP | Minneapolis–Saint Paul International Airport (USA)' },
  { value: 'BOS', name: 'BOS | Logan International Airport (USA)' },
  { value: 'SFO', name: 'SFO | San Francisco International Airport (USA)' },
  { value: 'DUB', name: 'DUB | Dublin Airport (Ireland)' },
  { value: 'ZRH', name: 'ZRH | Zurich Airport (Switzerland)' },
  { value: 'BRU', name: 'BRU | Brussels Airport (Belgium)' },
  { value: 'CPT', name: 'CPT | Cape Town International Airport (South Africa)' },
  { value: 'JNB', name: 'JNB | OR Tambo International Airport (South Africa)' },
  { value: 'NRT', name: 'NRT | Narita International Airport (Japan)' },
  { value: 'SVO', name: 'SVO | Sheremetyevo International Airport (Russia)' },
  { value: 'DOH', name: 'DOH | Hamad International Airport (Qatar)' },
  { value: 'AUH', name: 'AUH | Abu Dhabi International Airport (UAE)' },
  { value: 'DEL', name: 'DEL | Indira Gandhi International Airport (India)' },
  { value: 'BOM', name: 'BOM | Chhatrapati Shivaji Maharaj International Airport (India)' },
  { value: 'CGK', name: 'CGK | Soekarno–Hatta International Airport (Indonesia)' },
  { value: 'KUL', name: 'KUL | Kuala Lumpur International Airport (Malaysia)' },
  { value: 'ICN', name: 'ICN | Incheon International Airport (South Korea)' },
  { value: 'OSL', name: 'OSL | Oslo Gardermoen Airport (Norway)' },
  { value: 'ARN', name: 'ARN | Stockholm Arlanda Airport (Sweden)' },
  { value: 'HEL', name: 'HEL | Helsinki-Vantaa Airport (Finland)' },
  { value: 'CPH', name: 'CPH | Copenhagen Airport (Denmark)' },
  { value: 'TXL', name: 'TXL | Berlin Tegel Airport (Germany)' },
  { value: 'VIE', name: 'VIE | Vienna International Airport (Austria)' },
  { value: 'PRG', name: 'PRG | Václav Havel Airport Prague (Czech Republic)' },
  { value: 'LIS', name: 'LIS | Humberto Delgado Airport (Portugal)' },
  { value: 'WAW', name: 'WAW | Warsaw Chopin Airport (Poland)' },
  { value: 'SVO', name: 'SVO | Sheremetyevo International Airport (Russia)' },
  { value: 'THR', name: 'THR | Mehrabad International Airport (Iran)' },
  { value: 'CMN', name: 'CMN | Mohammed V International Airport (Morocco)' },
  { value: 'CAI', name: 'CAI | Cairo International Airport (Egypt)' },
];

export const MONTHS = [
  { value: '01', name: 'Janeiro' },
  { value: '02', name: 'Fevereiro' },
  { value: '03', name: 'Março' },
  { value: '04', name: 'Abril' },
  { value: '05', name: 'Maio' },
  { value: '06', name: 'Junho' },
  { value: '07', name: 'Julho' },
  { value: '08', name: 'Agosto' },
  { value: '09', name: 'Setembro' },
  { value: '10', name: 'Outubro' },
  { value: '11', name: 'Novembro' },
  { value: '12', name: 'Dezembro' },
];
