export const AIRPORT_CODES = [
  { value: 'ATL', name: 'Hartsfield–Jackson Atlanta (USA) - ATL' },
  { value: 'PEK', name: 'Beijing Capital (China) - PEK' },
  { value: 'LAX', name: 'Los Angeles (USA) - LAX' },
  { value: 'DXB', name: 'Dubai (UAE) - DXB' },
  { value: 'HND', name: 'Tokyo Haneda (Japan) - HND' },
  { value: 'ORD', name: 'O’Hare (USA) - ORD' },
  { value: 'LHR', name: 'London Heathrow (UK) - LHR' },
  { value: 'HKG', name: 'Hong Kong (Hong Kong) - HKG' },
  { value: 'PVG', name: 'Shanghai Pudong (China) - PVG' },
  { value: 'CDG', name: 'Charles de Gaulle (France) - CDG' },
  { value: 'DFW', name: 'Dallas/Fort Worth (USA) - DFW' },
  { value: 'AMS', name: 'Amsterdam Airport Schiphol (Netherlands) - AMS' },
  { value: 'FRA', name: 'Frankfurt am Main (Germany) - FRA' },
  { value: 'IST', name: 'Istanbul (Turkey) - IST' },
  { value: 'SIN', name: 'Singapore Changi (Singapore) - SIN' },
  { value: 'ICN', name: 'Incheon (South Korea) - ICN' },
  { value: 'JFK', name: 'John F. Kennedy (USA) - JFK' },
  { value: 'CAN', name: 'Guangzhou Baiyun (China) - CAN' },
  { value: 'DEN', name: 'Denver (USA) - DEN' },
  { value: 'BKK', name: 'Suvarnabhumi (Thailand) - BKK' },
  { value: 'MIA', name: 'Miami (USA) - MIA' },
  { value: 'MEX', name: 'Mexico City (Mexico) - MEX' },
  { value: 'GRU', name: 'São Paulo/Guarulhos (Brazil) - GRU' },
  { value: 'EZE', name: 'Ministro Pistarini (Argentina) - EZE' },
  { value: 'GIG', name: 'Rio de Janeiro/Galeão (Brazil) - GIG' },
  { value: 'BOG', name: 'El Dorado (Colombia) - BOG' },
  { value: 'SCL', name: 'Comodoro Arturo Merino Benítez (Chile) - SCL' },
  { value: 'LIM', name: 'Jorge Chávez (Peru) - LIM' },
  { value: 'PTY', name: 'Tocumen (Panama) - PTY' },
  { value: 'MUC', name: 'Munich (Germany) - MUC' },
  { value: 'BCN', name: 'Barcelona–El Prat (Spain) - BCN' },
  { value: 'MAD', name: 'Madrid–Barajas (Spain) - MAD' },
  { value: 'YYZ', name: 'Toronto Pearson (Canada) - YYZ' },
  { value: 'YVR', name: 'Vancouver (Canada) - YVR' },
  { value: 'SYD', name: 'Sydney Kingsford Smith (Australia) - SYD' },
  { value: 'MEL', name: 'Melbourne (Australia) - MEL' },
  { value: 'GUA', name: 'La Aurora (Guatemala) - GUA' },
  { value: 'UIO', name: 'Mariscal Sucre (Ecuador) - UIO' },
  { value: 'GYE', name: 'José Joaquín de Olmedo (Ecuador) - GYE' },
  { value: 'CUN', name: 'Cancun (Mexico) - CUN' },
  { value: 'PHX', name: 'Phoenix Sky Harbor (USA) - PHX' },
  { value: 'SEA', name: 'Seattle–Tacoma (USA) - SEA' },
  { value: 'CLT', name: 'Charlotte Douglas (USA) - CLT' },
  { value: 'LAS', name: 'Harry Reid (USA) - LAS' },
  { value: 'IAH', name: 'George Bush Intercontinental (USA) - IAH' },
  { value: 'MSP', name: 'Minneapolis–Saint Paul (USA) - MSP' },
  { value: 'BOS', name: 'Logan (USA) - BOS' },
  { value: 'SFO', name: 'San Francisco (USA) - SFO' },
  { value: 'DUB', name: 'Dublin (Ireland) - DUB' },
  { value: 'ZRH', name: 'Zurich (Switzerland) - ZRH' },
  { value: 'BRU', name: 'Brussels (Belgium) - BRU' },
  { value: 'CPT', name: 'Cape Town (South Africa) - CPT' },
  { value: 'JNB', name: 'OR Tambo (South Africa) - JNB' },
  { value: 'NRT', name: 'Narita (Japan) - NRT' },
  { value: 'SVO', name: 'Sheremetyevo (Russia) - SVO' },
  { value: 'DOH', name: 'Hamad (Qatar) - DOH' },
  { value: 'AUH', name: 'Abu Dhabi (UAE) - AUH' },
  { value: 'DEL', name: 'Indira Gandhi (India) - DEL' },
  { value: 'BOM', name: 'Chhatrapati Shivaji Maharaj (India) - BOM' },
  { value: 'CGK', name: 'Soekarno–Hatta (Indonesia) - CGK' },
  { value: 'KUL', name: 'Kuala Lumpur (Malaysia) - KUL' },
  { value: 'ICN', name: 'Incheon (South Korea) - ICN' },
  { value: 'OSL', name: 'Oslo Gardermoen (Norway) - OSL' },
  { value: 'ARN', name: 'Stockholm Arlanda (Sweden) - ARN' },
  { value: 'HEL', name: 'Helsinki-Vantaa (Finland) - HEL' },
  { value: 'CPH', name: 'Copenhagen (Denmark) - CPH' },
  { value: 'TXL', name: 'Berlin Tegel (Germany) - TXL' },
  { value: 'VIE', name: 'Vienna (Austria) - VIE' },
  { value: 'PRG', name: 'Václav Havel Airport Prague (Czech Republic) - PRG' },
  { value: 'LIS', name: 'Humberto Delgado (Portugal) - LIS' },
  { value: 'WAW', name: 'Warsaw Chopin (Poland) - WAW' },
  { value: 'SVO', name: 'Sheremetyevo (Russia) - SVO' },
  { value: 'THR', name: 'Mehrabad (Iran) - THR' },
  { value: 'CMN', name: 'Mohammed V (Morocco) - CMN' },
  { value: 'CAI', name: 'Cairo (Egypt) - CAI' },
];

export const MONTHS = [
  { value: '01', name: 'Janeiro' },
  { value: '02', name: 'Fevereiro' },
  { value: '03', name: 'Março' },
  { value: '04', name: 'Abril' },
  { value: '05', name: 'Maio' },
  { value: '06', name: 'Junho' },
  { value: '07', name: 'Julho' },
  { value: '08', name: 'Agosto' },
  { value: '09', name: 'Setembro' },
  { value: '10', name: 'Outubro' },
  { value: '11', name: 'Novembro' },
  { value: '12', name: 'Dezembro' },
];
